### ISSUE TITLE
Support for ordering results by strength of match

### ISSUE THREAD

**Issue by reubenjh** [ferrriii/JsonSearch#2]
Hey there! 

First of all, thank you for sharing this, it's a fantastic tool. You're a legend <3 

I've implemented it on my community deck building website for the card game Sorcery.

I just wanted to check whether you were interested in adding support for sorting the returned results by the strength of their match.

Example: On my cards page https://curiosa.io/cards when you search `minor explosion`, the two returned results are `Major Explosion` and `Minor Explosion`, however major appears first as it is first in the source array. 

Let me know what you think!

**Comment by ferrriii** [comment]
Hi Reuben,
Thanks, I'm happy to see someone is making something awesome with this library :)

Totally agree with you about the sort feature, I'll work on it for future releases.

**Comment by ferrriii** [comment]
Hi,
Sort option added in version [1.6.0](https://www.npmjs.com/package/search-array) https://github.com/ferrriii/JsonSearch/commit/b579a462230c6668ab8778dc5620968474779c0a 🎉
